apiVersion: apps/v1
kind: Deployment
metadata:
  name: senseibird-web
  namespace: senseibird
  labels:
    app: senseibird
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: senseibird
      track: green
  template:
    metadata:
      labels:
        app: senseibird
        track: green
    spec:
      containers:
        - name: web
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://senseibird-api:{{ .Values.backend.port }}"
            - name: HOSTNAME
              value: "0.0.0.0"

          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 40

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
