apiVersion: v1
kind: Config

clusters:
- name: minikube
  cluster:
    server: https://192.168.49.2:8443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1Ea3hOREUzTURJeE1Wb1hEVE0xTURreE16RTNNREl4TVZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUZ0ClZIQnFsS2o2TTdpcS9WRXFCcytiV2pDS0VsYmM0R2lyZ0ljcmhDbHgwZlZVaXo2SnhQTzlja1ZuUnNadWErRFcKOVMrb1o4S1RNV0krWU8raUNBbFp0SEhnTk5XL0JpQkl1UVBXUU1QNnlWNXU3QUd2MmYvYkpHQ3hpZjV1cGZ4RwphU1MxNGZtc0JrbHJOV2lLSEdnYllodVRyNG4zYlNJbDdsZUhtdHdQcVRkT1BodytsM2NCbm9ORy9KUEg1UnhyCkNGZEp0bDVrblhjMXdTdnUvYW1ZTDJqUitYRkNyQ2ZUMVZIbW1BQmcxc2VVbnhxbW8vYzNuMkZrejBFYWZleHIKb1BkZ24yK1N1NU9venFXZFkvMTZpYk5ndDRjMVliWGwrQ2IwbStKOFFNc2VGcjY0MjMyRDgwSGlSTVV2OC9UcgpFQ0FScnhoenNNUVN6THJma2VjQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUTWNVaGJEQkhFYiszSzBCY096V0tTUU92ZWpUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF1YXdONndqTgpnejd2UjBiYys4RTdteXNpVS81b2xPZm8vL0d0OGFINlgxeWFGYUxGbU53RXpVWlhBYXlHdkYxZktaT3dLRkNTCjhsUVdRY3VXcW5KL3JNcWRjeStrNmJISXI5UGQvSXFFV2ZNdWFQWEg0YldtZWJoSG5nNHRaVGsvVzhIRlJiL3MKWmhjUXhBd1FlTWxBdnJkblJNL3VIYnJsQi8vc09iODNBV0ZWWm45Y29aUlhUODBGMlQ5cWZnckRGc2ZKQmYwWApCdlBhM2FQSnpXUXNFQ3pnY01SM0diUFlBN0pDUTF4dG52K044ck5UZ3hrRjQ5MVVRTi9CcFd1d2xMT2NQWC9DCkpTdjNoQmdYczgvbi95MmRNSCtCTnEwczhiaHN6VjdQQXFueDJ0UFFzOVZsZlVUdnlQYXZMYzVYNnJqTEFYU0cKN0ZMUnJxK0JJYmJMcHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

users:
- name: jenkins-helm
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InlpR3FVelNLMUo5Q2dJSDhCOVJXZG5LRkdyZnZmMXdqaFBnUG9ZN2ZJcFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtaGVsbS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJqZW5raW5zLWhlbG0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI3MTY0NDYwMy0xMjg2LTQzZjctOTRjMS03MGJjZDIyNWY1MDUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6amVua2luczpqZW5raW5zLWhlbG0ifQ.QYAOChO5ahulo-kMtyr3N7oCSzTD3ek4COkdtZrgz4KNuzHvvA9blKFJhRTv59g56-WV2BOiOXKWJ2KHzDcn1EmZQn2p70Qv-o2lj2fKh-Ol_clztlp22LqM0Nc-owmXczFur6MsX9seznSRBjjqFEX6L_Qi1aCDt5yTi5tl1cViW03kvK50dnDPloL9i-y5hUC2fBqwcrjxzgMi0LYNmsLWk0EcyEemCLMv8gdurnFO_3ak3QJIJIXkbypfvcxK7oaQZlY9Zft5CMuvTYi26hYzLpgVsiQHwaiVUv9xxOO3FiYGJN-n7JOl1J432SQVRiqdkQixwmepRlYao1XlFA

contexts:
- name: jenkins-helm
  context:
    cluster: minikube
    user: jenkins-helm
    namespace: senseibird

current-context: jenkins-helm
