apiVersion: v1
kind: Config
clusters:
  - name: portable-cluster
    cluster:
      server: https://127.0.0.1:58263
      certificate-authority-data: <pega_aquí_el_valor_de_$caData>
contexts:
  - name: jenkins-helm
    context:
      cluster: portable-cluster
      user: jenkins-helm
      namespace: senseibird
current-context: jenkins-helm
users:
  - name: jenkins-helm
    user:
      token: <pega_aquí_el_valor_de_$token>
