apiVersion: v1
kind: Pod
metadata:
  name: badpod
spec:
  containers:
    - name: test
      image: nginx:latest              
      securityContext:
        runAsUser: 0                  
      # Falta readOnlyRootFilesystem 
      # Falta resources                

# kubectl apply -f k8s\policies\badpod-ejemplo.yaml